# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
   lane :begin do
      puts("begin running test")
   end

   desc "Run unit and ui tests"
   lane :runTests do
      run_tests()
   end

    desc "Build application"
    lane :buildApp do
    gym(
      workspace: "TCB-CICD.xcworkspace",
      scheme: "TCB-CICD",
      clean: true,
      skip_archive: true,
    )
    end

    lane :podInstall do 
        cocoapods(
          clean_install: true,
        )
    end

   lane :end do
      puts("end running test")
   end
end
